#!/bin/bash

function benchmark {
    P=$1
    start=$2
    stop=$3
    step=$(echo "($stop - $start) / 20" | bc)
    for ((i=1; i<=20; i++)); do
        B=$(echo "$start + $i * ($stop - $start) / 20" | bc)
        echo "Going from $start to $B"
        mpirun -np $P ${BASEDIR}/../program/parallel $start $B >> run_time_${P}_${start}_${stop}.txt
    done
}

BASEDIR=$(dirname $0)

benchmark 1 2 100
benchmark 1 2 1000000
#benchmark 1 2 1000000000
#
#benchmark 2 2 100
#benchmark 2 2 1000000
#benchmark 2 2 1000000000
#
#benchmark 4 2 100
#benchmark 4 2 1000000
#benchmark 4 2 1000000000
#
#benchmark 8 2 100
#benchmark 8 2 1000000
#benchmark 8 2 1000000000

